version: '3'
services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile
  backend: &backend
    <<: *app
    volumes:
      - ..:/workspace:cached
  web:
    <<: *backend
    tty: true
    command: sleep infinity
    ports:
      - "3000:3000"
